#logging:
#    level:
#        com:
#            khmersolution:
#                moduler: DEBUG
#        org:
#            hibernate:
#                SQL: debug
#                type:
#                    descriptor:
#                        sql: trace
#    pattern:
#        console: '%clr(%d{HH:mm:ss}){magenta} %-5level - %clr(%msg%n){cyan}'
#        file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
security:
    oauth2:
        resourceId: oauth2-jwt-resource
server:
    port: ${PORT:8080}
    contextPath: /
spring:
    data:
        rest:
            basePath: /rest/api
    datasource:
        # driverClassName: org.postgresql.Driver
        # maxActive: 5
        # password: postgres
        # url: jdbc:postgresql://localhost:5432/postgres
        # username: postgres
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                # dialect: org.hibernate.dialect.PostgreSLDialect
                dialect: org.hibernate.dialect.H2Dialect
                formatSql: false
        showSql: false
###### Custom Swagger Properties
swagger:
    apiInfo:
        contactEmail: ravuthz@gmail.com
        contactName: ravuthz@gmail.com
        contactUrl: http://github.com/ravuthz/user-management-api
        description: Users Restful API with Spring Boot + Spring Data + Spring Rest.
        license: Apache 2.0
        licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
        termOfServiceUrl: http://swagger.io/terms/
        title: User Management API
        version: 1.0.0
    defaultKey:
        page: page
        size: size
        sort: sort
    defaultValue:
        page: 0
        size: 20
        sort: id,desc

endpoints:
    cors:
        allowed-origins: *
        allowed-methods: GET,PUT,POST,PATCH,DELETE
